# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - staging

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - env:
        # Credentials used to perform the release and commit the updated assets
        # to the repository.
        # Required: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Checkout
      uses: actions/checkout@v1
    - env:
        # Credentials used to perform the release and commit the updated assets
        # to the repository.
        # Required: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: samof76/release-me-action@master
      name: Release
      with:
        # Configure Semantic Release branches parameter:
        # https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#branches-properties
        #
        # If not specified, Semantic Release will use its default branches
        # configuration, specified in the API documentation:
        # https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches
        release-branches: '["master",{"name":"staging","prerelease":true}]'
        # Commit the new line separated glob patterns to the repository as part
        # of the release process.
        plugins: '["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", "@semantic-release/github"]'
        # Run semantic release in dry-run mode.
        # Default: false
        dry-run: false
        # Bump the node module version and commit the changed package files to the
        # repository as part of the release process.
        # Default: false
        node-module: false
        # Do not create changelog
        changelog: false
